### ISSUE TITLE
Is st.empty() possible?

### ISSUE THREAD

**Issue by thomas-happify** [franekp/streamlit-permalink#4]
First off, this is a really awesome helper library! thanks a lot for doing this.

I'm wondering if `stp.empty()` is possible? because sometimes I want to have a placeholder to arrange the streamlit UI.

Thanks!

**Comment by franekp** [comment]
Yes, using `st.empty()` just works. The reason there is `stp.form()` but not `stp.empty()`, `stp.container()`, etc. is because forms behave differently and update their state only when submit button is pressed, so the logic for updating the url must be tied to the submit button and not individual components.

I have added a catch-all `__getattr__` such that `stp.empty()`, `stp.container()`, etc. just forward to the `st` namespace.
